package JNProgrammer

import "log"

const (
	E_STATUS_OK = iota
	E_STATUS_ERROR
	E_STATUS_ERROR_WRITING
	E_STATUS_ERROR_READING
	E_STATUS_FAILED_TO_OPEN_FILE
	E_STATUS_BAD_PARAMETER
	E_STATUS_NULL_PARAMETER
	E_STATUS_INCOMPATIBLE
)

var Logger *log.Logger

type VERVOSITY uint64
var LogLevel VERVOSITY

const (
	E_VERVOSITY_NONE VERVOSITY = iota
	E_VERVOSITY_ERROR
	E_VERVOSITY_WARN
	E_VERVOSITY_INFO
	E_VERVOSITY_VERVOSE
)

var DEBUG bool